spring:
  application:
    name: be
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope: email, public_profile
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  task:
    execution:
      pool:
        core-size: 5           # Số lượng thread tối thiểu
        max-size: 20           # Số lượng thread tối đa
        queue-capacity: 100    # Hàng đợi chờ xử lý
      thread-name-prefix: "MyAsync-Task-" # Tiền tố để dễ debug
identity:
  expire-at-minute: 30
  expire-rt-day: 7
  secret-key: ${SECRET_KEY}
  audience: my-frontend-app

cloudflare:
  r2:
    account-id: ${CLOUDFLARE_R2_ACCOUNT_ID}
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY}
    bucket: ${CLOUDFLARE_R2_BUCKET}
    public-url: ${CLOUDFLARE_R2_PUBLIC_URL}
