spring:
  application:
    name: be
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

identity:
  expire-at-minute: 30
  expire-rt-day: 7
  secret-key: ${SECRET_KEY}
  audience: my-frontend-app

