server:
  port: 8080

spring:
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
app:
  frontend:
    url: http://localhost:3000
  cookie:
    secure: false
    same-site: Lax
