server:
  port: 8080

spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  data:
    redis:
      url: ${REDIS_URL}
app:
  frontend:
    url: https://thanhblog.online
  cors:
    allowed-origins: https://thanhblog.online,https://www.thanhblog.online
  cookie:
    secure: true
    same-site: LAX
  domain: thanhblog.online
